export interface Neighborhood {
    NEIGHBORHOOD_ID: number,
    NEIGHBORHOOD: string,
    LAT: number,
    LONG: number,
    GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    TREND_SCORE: "A" | "B" | "C" | "D" | "0",
    ONEBR_GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    ONEBR_PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    ONEBR_PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    ONEBR_TREND_SCORE: "A" | "B" | "C" | "D" | "0",
    TWOBR_GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    TWOBR_PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    TWOBR_PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    TWOBR_TREND_SCORE: "A" | "B" | "C" | "D" | "0",
    THREEBR_GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    THREEBR_PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    THREEBR_PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    THREEBR_TREND_SCORE: "A" | "B" | "C" | "D" | "0",
    FOURBR_GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    FOURBR_PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    FOURBR_PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    FOURBR_TREND_SCORE: "A" | "B" | "C" | "D" | "0",
    FIVEBR_GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    FIVEBR_PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    FIVEBR_PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    FIVEBR_TREND_SCORE: "A" | "B" | "C" | "D" | "0",
    SIXBR_GENERAL_SCORE: "A" | "B" | "C" | "D" | "0",
    SIXBR_PRECENTAGE_SCORE: "A" | "B" | "C" | "D" | "0",
    SIXBR_PERCISION_SCORE: "A" | "B" | "C" | "D" | "0",
    SIXBR_TREND_SCORE: "A" | "B" | "C" | "D" | "0"
}